=== BambaDeme/examen-xml/examens/Examen.dtd
<!ELEMENT Examen (module, date, Questions)>
<!ATTLIST Examen code NMTOKEN #REQUIRED>
<!ELEMENT module (#PCDATA)>
<!ELEMENT date EMPTY>
<!ATTLIST date mois (Jan| Fev| Mars| Avril| Mai| Juin| Juillet| Aout| Sept| Octo| Nov| Dec) #REQUIRED annee CDATA #REQUIRED>
<!ELEMENT Questions (Question,Question,Question,Question?)>
<!ELEMENT Question (partie+)>
<!ELEMENT partie (#PCDATA|partie)*>

=== BambaDeme/examen-xml/examens/Examen32154.xml
<?xml version="1.0"?>
<!DOCTYPE Examen SYSTEM "Examen.dtd">
<Examen code="12">
    <module>Données Sémi Structurées</module>
    <date mois="Nov" annee="2021"/>
    <Questions>
        <Question>
            <partie>
            Definir xml
            </partie>
        </Question>

        <Question>
            <partie>
            </partie>
        </Question>
 
        <Question>
            <partie>
            </partie>
        </Question>
     </Questions>
</Examen>

=== BambaDeme/examen-xml/examens/réseau.xml
<?xml version="1.0"?>
<!DOCTYPE Examen SYSTEM "Examen.dtd">
<Examen code="12">
    <module>Données Sémi Structurées</module>
    <date mois="Nov" annee="2021"/>
    <Questions>
        <Question>
            <partie>
            Processus
            </partie>
        </Question>

        <Question>
            <partie>
            thread
            </partie>
	    <partie>
            </partie>
        </Question>
 
        <Question>
            <partie>
            </partie>
        </Question>
     </Questions>
</Examen>

=== BambaDeme/examen-xml/examens/Examen.xml
<?xml version="1.0"?>
<!DOCTYPE Examen SYSTEM "Examen.dtd">
<Examen code="12">
    <module>Données Sémi Structurées</module>
    <date mois="Nov" annee="2021"/>
    <Questions>
       <Question>
            <partie>
            Definir xml
            </partie>
            <partie>
            Qui l'a crée
            </partie>
        </Question>

        <Question>
            <partie>
            Quelle est l'utilité de xml
            </partie>
            <partie>
            Teste
            </partie>
        </Question>
 
        <Question>
            <partie>
            sa différence avec html 
            </partie>
        </Question>
     </Questions>
</Examen>
